color: null
fieldLayouts:
  482c524a-895e-47e5-a80b-22ef6f7a2bd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b27b0faf-fd2a-459b-995f-5f8d50a6436e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 767066dc-a817-48f9-a239-67b3e18fa302
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7ec0fe3-e0bc-474d-837d-3159984e36f3 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f21e90e7-f101-44f3-bc0c-54dcfe3c7799
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5295452a-cfcc-44d9-b94d-d408fee259c3
        userCondition: null
handle: checkoutShipping
hasTitleField: true
icon: null
name: 'Checkout: Shipping'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
