color: null
fieldLayouts:
  3474d9f8-95a1-4792-b81f-3c0cfd36d4ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a336ae76-d15e-4d55-a35b-e32588160bba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4618ebbc-ed9f-4632-8648-dbbfafc12ce5 # Heading
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 285b26c6-8b36-473a-9e21-6c40e17b14af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 520350fa-6eaf-4bc0-9568-687055d5b462 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: Form
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50bdbb96-cd19-4398-9e33-5e08f9142eb9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4616725f-bb07-4e36-bd8a-1ee016952735
        userCondition: null
handle: form
hasTitleField: false
icon: null
name: Form
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
