color: null
fieldLayouts:
  bd5cdfbd-9eb4-42c1-a500-37732ab3f1c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 18c642cf-5f6d-4d34-bceb-24b834bdd967
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d6666f58-4d11-4bd3-b5bd-bc92b52a538c # Products
            handle: null
            includeInCards: true
            instructions: null
            label: Products
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e03db92-e525-4e6f-890e-bd74e540862b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b89de1a7-7320-4ddd-8c5c-6bce35abf395
        userCondition: null
handle: products
hasTitleField: false
icon: null
name: Products
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
