columnSuffix: zhgorwis
handle: businessAddress
instructions: 'Enter the shop’s physical street address.'
name: 'Business Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
