columnSuffix: null
handle: buttonUrl
instructions: 'Use this field if you require linking to a custom URL that is not an entry or category.'
name: 'Button - Button - Button URL'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
