columnSuffix: null
handle: intro
instructions: 'Enable to display slightly larger text for an introduction.'
name: 'Content Blocks - Body - Intro'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
