defaultPlacement: end
enableVersioning: true
entryTypes:
  - a853d93f-f289-4671-b5d1-61a8099d5abb # Articles Landing
handle: articlesLanding
maxAuthors: 1
name: 'Articles Landing'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/articles/index
    uriFormat: articles
type: single
