defaultPlacement: end
enableVersioning: true
entryTypes:
  - 74c53fbd-78e5-4125-87f7-38c75efce7d3 # Cart
handle: cart
maxAuthors: 1
name: Cart
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/cart
    uriFormat: cart
type: single
