defaultPlacement: end
enableVersioning: true
entryTypes:
  - 42b7e744-7597-4a2c-991e-8ba00290c19f # Checkout
handle: checkout
maxAuthors: 1
name: Checkout
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/checkout
    uriFormat: checkout
type: single
