defaultPlacement: end
enableVersioning: true
entryTypes:
  - c3af370d-8c71-468a-b040-1583d3342b27 # Checkout: Summary
handle: checkoutSummary
maxAuthors: 1
name: 'Checkout: Summary'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: true
    template: _views/checkout/summary
    uriFormat: checkout/summary
type: single
