defaultPlacement: end
enableVersioning: true
entryTypes:
  - be4e2a2f-de59-4443-a08e-476d20bc36d6 # Plans
handle: plans
maxAuthors: 1
name: Plans
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  5712e1f3-7800-493e-b74b-c2887dc25c81: # Spoke & Chain
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
